"""Single taxonomy of validation codes. FAILED = defect in an artifact; BLOCKED = missing input/decision."""
from dataclasses import dataclass

FAILED, BLOCKED, PASSED = "FAILED", "BLOCKED", "PASSED"

# Required by the master prompt
ORPHAN_SCREEN = "ORPHAN_SCREEN"
ORPHAN_STITCH_ARTIFACT = "ORPHAN_STITCH_ARTIFACT"
MISSING_FLOW_REFERENCE = "MISSING_FLOW_REFERENCE"
MISSING_REQUIREMENT_LINEAGE = "MISSING_REQUIREMENT_LINEAGE"
MULTIPLE_ACTIVE_STITCH_PROJECTS = "MULTIPLE_ACTIVE_STITCH_PROJECTS"
WRONG_STITCH_PROJECT = "WRONG_STITCH_PROJECT"
STALE_STITCH_REFERENCE = "STALE_STITCH_REFERENCE"
STALE_FIGMA_REFERENCE = "STALE_FIGMA_REFERENCE"
STITCH_FIGMA_DIVERGENCE = "STITCH_FIGMA_DIVERGENCE"
MISSING_GOVERNED_DESIGN = "MISSING_GOVERNED_DESIGN"
MISSING_SCREEN_STATE = "MISSING_SCREEN_STATE"
MISSING_RESPONSIVE_RULE = "MISSING_RESPONSIVE_RULE"
MISSING_ACCESSIBILITY_REQUIREMENT = "MISSING_ACCESSIBILITY_REQUIREMENT"
MISSING_COMPONENT_REFERENCE = "MISSING_COMPONENT_REFERENCE"
MISSING_TOKEN_REFERENCE = "MISSING_TOKEN_REFERENCE"
BLOCKING_OPEN_QUESTION = "BLOCKING_OPEN_QUESTION"

# Justified additions (see 03-CHANGE-DESIGN.md §3)
MISSING_INITIATIVE = "MISSING_INITIATIVE"
MISSING_STITCH_PROJECT = "MISSING_STITCH_PROJECT"
DANGLING_REFERENCE = "DANGLING_REFERENCE"
DUPLICATE_ID = "DUPLICATE_ID"
PLACEHOLDER_REFERENCE = "PLACEHOLDER_REFERENCE"
HUMAN_REVIEW_PENDING = "HUMAN_REVIEW_PENDING"
OKF_INVALID = "OKF_INVALID"
MISSING_HANDOFF = "MISSING_HANDOFF"
MISSING_HANDOFF_SECTION = "MISSING_HANDOFF_SECTION"
INVALID_ARTIFACT_REF = "INVALID_ARTIFACT_REF"
UNVERIFIED_ARTIFACT_REF = "UNVERIFIED_ARTIFACT_REF"

SEVERITY = {
    ORPHAN_SCREEN: FAILED, ORPHAN_STITCH_ARTIFACT: FAILED, MISSING_FLOW_REFERENCE: BLOCKED,
    MISSING_REQUIREMENT_LINEAGE: BLOCKED, MULTIPLE_ACTIVE_STITCH_PROJECTS: FAILED,
    WRONG_STITCH_PROJECT: FAILED, STALE_STITCH_REFERENCE: FAILED, STALE_FIGMA_REFERENCE: FAILED,
    STITCH_FIGMA_DIVERGENCE: BLOCKED, MISSING_GOVERNED_DESIGN: BLOCKED, MISSING_SCREEN_STATE: FAILED,
    MISSING_RESPONSIVE_RULE: FAILED, MISSING_ACCESSIBILITY_REQUIREMENT: FAILED,
    MISSING_COMPONENT_REFERENCE: FAILED, MISSING_TOKEN_REFERENCE: FAILED, BLOCKING_OPEN_QUESTION: BLOCKED,
    MISSING_INITIATIVE: BLOCKED, MISSING_STITCH_PROJECT: BLOCKED, DANGLING_REFERENCE: FAILED,
    DUPLICATE_ID: FAILED, PLACEHOLDER_REFERENCE: BLOCKED, HUMAN_REVIEW_PENDING: BLOCKED,
    OKF_INVALID: FAILED, MISSING_HANDOFF: BLOCKED, MISSING_HANDOFF_SECTION: FAILED,
    INVALID_ARTIFACT_REF: FAILED, UNVERIFIED_ARTIFACT_REF: BLOCKED,
}


@dataclass(frozen=True)
class Finding:
    code: str
    subject: str
    message: str

    @property
    def severity(self) -> str:
        return SEVERITY[self.code]

    def as_dict(self) -> dict:
        return {"code": self.code, "subject": self.subject, "severity": self.severity, "message": self.message}


def overall(findings) -> str:
    """FAILED prevails over BLOCKED; no findings means PASSED."""
    sev = {f.severity for f in findings}
    return FAILED if FAILED in sev else BLOCKED if BLOCKED in sev else PASSED
